# Generated by Django 4.1 on 2022-08-05 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactor",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date received"
            ),
            preserve_default=False,
        ),
    ]
