# Generated by Django 4.1 on 2022-08-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contactor_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactor",
            name="date",
        ),
    ]
