# Generated by Django 4.1 on 2022-08-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contactor",
        ),
    ]
